/*
 * This file is generated by jOOQ.
 */
package com.bd.jooq.tables;


import com.bd.jooq.DefaultSchema;
import com.bd.jooq.Keys;
import com.bd.jooq.tables.records.AlumnoRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Alumno extends TableImpl<AlumnoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>alumno</code>
     */
    public static final Alumno ALUMNO = new Alumno();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlumnoRecord> getRecordType() {
        return AlumnoRecord.class;
    }

    /**
     * The column <code>alumno.id_alumno</code>.
     */
    public final TableField<AlumnoRecord, Integer> ID_ALUMNO = createField(DSL.name("id_alumno"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>alumno.nombre</code>.
     */
    public final TableField<AlumnoRecord, String> NOMBRE = createField(DSL.name("nombre"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>alumno.apellido_paterno</code>.
     */
    public final TableField<AlumnoRecord, String> APELLIDO_PATERNO = createField(DSL.name("apellido_paterno"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>alumno.apellido_materno</code>.
     */
    public final TableField<AlumnoRecord, String> APELLIDO_MATERNO = createField(DSL.name("apellido_materno"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>alumno.edad</code>.
     */
    public final TableField<AlumnoRecord, Integer> EDAD = createField(DSL.name("edad"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>alumno.curp</code>.
     */
    public final TableField<AlumnoRecord, String> CURP = createField(DSL.name("curp"), SQLDataType.VARCHAR(18).nullable(false), this, "");

    /**
     * The column <code>alumno.grado</code>.
     */
    public final TableField<AlumnoRecord, String> GRADO = createField(DSL.name("grado"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>alumno.grupo</code>.
     */
    public final TableField<AlumnoRecord, String> GRUPO = createField(DSL.name("grupo"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>alumno.sexo</code>.
     */
    public final TableField<AlumnoRecord, String> SEXO = createField(DSL.name("sexo"), SQLDataType.VARCHAR(1), this, "");

    private Alumno(Name alias, Table<AlumnoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Alumno(Name alias, Table<AlumnoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>alumno</code> table reference
     */
    public Alumno(String alias) {
        this(DSL.name(alias), ALUMNO);
    }

    /**
     * Create an aliased <code>alumno</code> table reference
     */
    public Alumno(Name alias) {
        this(alias, ALUMNO);
    }

    /**
     * Create a <code>alumno</code> table reference
     */
    public Alumno() {
        this(DSL.name("alumno"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<AlumnoRecord, Integer> getIdentity() {
        return (Identity<AlumnoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AlumnoRecord> getPrimaryKey() {
        return Keys.ALUMNO__PK_ALUMNO;
    }

    @Override
    public List<UniqueKey<AlumnoRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ALUMNO__UK_ALUMNO_53808642);
    }

    @Override
    public Alumno as(String alias) {
        return new Alumno(DSL.name(alias), this);
    }

    @Override
    public Alumno as(Name alias) {
        return new Alumno(alias, this);
    }

    @Override
    public Alumno as(Table<?> alias) {
        return new Alumno(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Alumno rename(String name) {
        return new Alumno(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Alumno rename(Name name) {
        return new Alumno(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Alumno rename(Table<?> name) {
        return new Alumno(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Alumno where(Condition condition) {
        return new Alumno(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Alumno where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Alumno where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Alumno where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Alumno where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Alumno where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Alumno where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Alumno where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Alumno whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Alumno whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
