/*
 * This file is generated by jOOQ.
 */
package com.bd.jooq.tables.records;


import com.bd.jooq.tables.Alumno;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlumnoRecord extends UpdatableRecordImpl<AlumnoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>alumno.id_alumno</code>.
     */
    public void setIdAlumno(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>alumno.id_alumno</code>.
     */
    public Integer getIdAlumno() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>alumno.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>alumno.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>alumno.apellido_paterno</code>.
     */
    public void setApellidoPaterno(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>alumno.apellido_paterno</code>.
     */
    public String getApellidoPaterno() {
        return (String) get(2);
    }

    /**
     * Setter for <code>alumno.apellido_materno</code>.
     */
    public void setApellidoMaterno(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>alumno.apellido_materno</code>.
     */
    public String getApellidoMaterno() {
        return (String) get(3);
    }

    /**
     * Setter for <code>alumno.edad</code>.
     */
    public void setEdad(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>alumno.edad</code>.
     */
    public Integer getEdad() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>alumno.curp</code>.
     */
    public void setCurp(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>alumno.curp</code>.
     */
    public String getCurp() {
        return (String) get(5);
    }

    /**
     * Setter for <code>alumno.grado</code>.
     */
    public void setGrado(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>alumno.grado</code>.
     */
    public String getGrado() {
        return (String) get(6);
    }

    /**
     * Setter for <code>alumno.grupo</code>.
     */
    public void setGrupo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>alumno.grupo</code>.
     */
    public String getGrupo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>alumno.sexo</code>.
     */
    public void setSexo(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>alumno.sexo</code>.
     */
    public String getSexo() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlumnoRecord
     */
    public AlumnoRecord() {
        super(Alumno.ALUMNO);
    }

    /**
     * Create a detached, initialised AlumnoRecord
     */
    public AlumnoRecord(Integer idAlumno, String nombre, String apellidoPaterno, String apellidoMaterno, Integer edad, String curp, String grado, String grupo, String sexo) {
        super(Alumno.ALUMNO);

        setIdAlumno(idAlumno);
        setNombre(nombre);
        setApellidoPaterno(apellidoPaterno);
        setApellidoMaterno(apellidoMaterno);
        setEdad(edad);
        setCurp(curp);
        setGrado(grado);
        setGrupo(grupo);
        setSexo(sexo);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AlumnoRecord
     */
    public AlumnoRecord(com.bd.jooq.tables.pojos.Alumno value) {
        super(Alumno.ALUMNO);

        if (value != null) {
            setIdAlumno(value.getIdAlumno());
            setNombre(value.getNombre());
            setApellidoPaterno(value.getApellidoPaterno());
            setApellidoMaterno(value.getApellidoMaterno());
            setEdad(value.getEdad());
            setCurp(value.getCurp());
            setGrado(value.getGrado());
            setGrupo(value.getGrupo());
            setSexo(value.getSexo());
            resetChangedOnNotNull();
        }
    }
}
