/*
 * This file is generated by jOOQ.
 */
package com.bd.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Alumno implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer idAlumno;
    private String nombre;
    private String apellidoPaterno;
    private String apellidoMaterno;
    private Integer edad;
    private String curp;
    private String grado;
    private String grupo;
    private String sexo;

    public Alumno() {}

    public Alumno(Alumno value) {
        this.idAlumno = value.idAlumno;
        this.nombre = value.nombre;
        this.apellidoPaterno = value.apellidoPaterno;
        this.apellidoMaterno = value.apellidoMaterno;
        this.edad = value.edad;
        this.curp = value.curp;
        this.grado = value.grado;
        this.grupo = value.grupo;
        this.sexo = value.sexo;
    }

    public Alumno(
        Integer idAlumno,
        String nombre,
        String apellidoPaterno,
        String apellidoMaterno,
        Integer edad,
        String curp,
        String grado,
        String grupo,
        String sexo
    ) {
        this.idAlumno = idAlumno;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.edad = edad;
        this.curp = curp;
        this.grado = grado;
        this.grupo = grupo;
        this.sexo = sexo;
    }

    /**
     * Getter for <code>alumno.id_alumno</code>.
     */
    public Integer getIdAlumno() {
        return this.idAlumno;
    }

    /**
     * Setter for <code>alumno.id_alumno</code>.
     */
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }

    /**
     * Getter for <code>alumno.nombre</code>.
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Setter for <code>alumno.nombre</code>.
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * Getter for <code>alumno.apellido_paterno</code>.
     */
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }

    /**
     * Setter for <code>alumno.apellido_paterno</code>.
     */
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    /**
     * Getter for <code>alumno.apellido_materno</code>.
     */
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }

    /**
     * Setter for <code>alumno.apellido_materno</code>.
     */
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    /**
     * Getter for <code>alumno.edad</code>.
     */
    public Integer getEdad() {
        return this.edad;
    }

    /**
     * Setter for <code>alumno.edad</code>.
     */
    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    /**
     * Getter for <code>alumno.curp</code>.
     */
    public String getCurp() {
        return this.curp;
    }

    /**
     * Setter for <code>alumno.curp</code>.
     */
    public void setCurp(String curp) {
        this.curp = curp;
    }

    /**
     * Getter for <code>alumno.grado</code>.
     */
    public String getGrado() {
        return this.grado;
    }

    /**
     * Setter for <code>alumno.grado</code>.
     */
    public void setGrado(String grado) {
        this.grado = grado;
    }

    /**
     * Getter for <code>alumno.grupo</code>.
     */
    public String getGrupo() {
        return this.grupo;
    }

    /**
     * Setter for <code>alumno.grupo</code>.
     */
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }

    /**
     * Getter for <code>alumno.sexo</code>.
     */
    public String getSexo() {
        return this.sexo;
    }

    /**
     * Setter for <code>alumno.sexo</code>.
     */
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Alumno other = (Alumno) obj;
        if (this.idAlumno == null) {
            if (other.idAlumno != null)
                return false;
        }
        else if (!this.idAlumno.equals(other.idAlumno))
            return false;
        if (this.nombre == null) {
            if (other.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(other.nombre))
            return false;
        if (this.apellidoPaterno == null) {
            if (other.apellidoPaterno != null)
                return false;
        }
        else if (!this.apellidoPaterno.equals(other.apellidoPaterno))
            return false;
        if (this.apellidoMaterno == null) {
            if (other.apellidoMaterno != null)
                return false;
        }
        else if (!this.apellidoMaterno.equals(other.apellidoMaterno))
            return false;
        if (this.edad == null) {
            if (other.edad != null)
                return false;
        }
        else if (!this.edad.equals(other.edad))
            return false;
        if (this.curp == null) {
            if (other.curp != null)
                return false;
        }
        else if (!this.curp.equals(other.curp))
            return false;
        if (this.grado == null) {
            if (other.grado != null)
                return false;
        }
        else if (!this.grado.equals(other.grado))
            return false;
        if (this.grupo == null) {
            if (other.grupo != null)
                return false;
        }
        else if (!this.grupo.equals(other.grupo))
            return false;
        if (this.sexo == null) {
            if (other.sexo != null)
                return false;
        }
        else if (!this.sexo.equals(other.sexo))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idAlumno == null) ? 0 : this.idAlumno.hashCode());
        result = prime * result + ((this.nombre == null) ? 0 : this.nombre.hashCode());
        result = prime * result + ((this.apellidoPaterno == null) ? 0 : this.apellidoPaterno.hashCode());
        result = prime * result + ((this.apellidoMaterno == null) ? 0 : this.apellidoMaterno.hashCode());
        result = prime * result + ((this.edad == null) ? 0 : this.edad.hashCode());
        result = prime * result + ((this.curp == null) ? 0 : this.curp.hashCode());
        result = prime * result + ((this.grado == null) ? 0 : this.grado.hashCode());
        result = prime * result + ((this.grupo == null) ? 0 : this.grupo.hashCode());
        result = prime * result + ((this.sexo == null) ? 0 : this.sexo.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Alumno (");

        sb.append(idAlumno);
        sb.append(", ").append(nombre);
        sb.append(", ").append(apellidoPaterno);
        sb.append(", ").append(apellidoMaterno);
        sb.append(", ").append(edad);
        sb.append(", ").append(curp);
        sb.append(", ").append(grado);
        sb.append(", ").append(grupo);
        sb.append(", ").append(sexo);

        sb.append(")");
        return sb.toString();
    }
}
