/*
 * This file is generated by jOOQ.
 */
package com.bd.jooq;


import com.bd.jooq.tables.Alumno;
import com.bd.jooq.tables.records.AlumnoRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AlumnoRecord> ALUMNO__PK_ALUMNO = Internal.createUniqueKey(Alumno.ALUMNO, DSL.name("pk_alumno"), new TableField[] { Alumno.ALUMNO.ID_ALUMNO }, true);
    public static final UniqueKey<AlumnoRecord> ALUMNO__UK_ALUMNO_53808642 = Internal.createUniqueKey(Alumno.ALUMNO, DSL.name("uk_alumno_53808642"), new TableField[] { Alumno.ALUMNO.CURP }, true);
}
