/*
 * This file is generated by jOOQ.
 */
package com.bd.jooq;


import com.bd.jooq.tables.Alumno;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>alumno</code>.
     */
    public static final Alumno ALUMNO = Alumno.ALUMNO;
}
